name: clang

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Install tools
      run: |
        sudo apt update
        sudo apt --yes install clang cmake valgrind

    - name: Build
      run: |
        mkdir out
        cd out
        export CC=/usr/bin/clang
        export CXX=/usr/bin/clang++
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make

    - name: Test
      run: |
        cd out
        valgrind --leak-check=yes ./wscs_tests

