name: cppcheck

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Install Cppcheck
      run: |
        sudo apt update
        sudo apt --yes install cppcheck

    - name: Static analysis
      run: |
        cppcheck --project=wscs.cppcheck
