name: gcc

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Prerequisites
      run: |
        sudo apt update
        sudo apt install g++ cmake valgrind

    - name: Build
      run: |
        mkdir out
        cd out
        export CC=/usr/bin/gcc
        export CXX=/usr/bin/g++
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        make

    - name: Test
      run: |
        cd out
        valgrind --leak-check=yes ./wscs_tests

