name: msvc

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: |
        mkdir out
        cd out
        cmake -DCMAKE_BUILD_TYPE=Debug ..
        MSBuild.exe wscs.sln /t:Rebuild /m